Band crud
kir-dev/mmmk-web pull request #11
Opened 2024-11-27 20:19 UTC by DankaMarci

Migrated the prisma schema to add a default value to the bandmembership's status attribute.

2024-12-10 15:05 UTC, justnyx requested changes
I've left some comments, please fix where necessary.

2024-12-10 15:05 UTC, justnyx commented on apps/backend/src/band/band.service.ts
> +      throw new NotFoundException('No members found');
If a band has no members, shouldn't it be deleted? If so, how should this be implemented? @balintking

2024-12-10 15:05 UTC, justnyx commented on apps/backend/src/band/band.service.ts
> +      const bandmemberships = await this.prisma.bandMembership.findMany({ where: { bandId: id } });
Only those with `ACCEPTED` membership status should be returned in my opinion.

2024-12-12 11:45 UTC, balintking requested changes
Remove manual Error throws

2024-12-12 14:09 UTC, FearsomeRover approved these changes

2024-12-12 14:12 UTC, balintking approved these changes

2024-12-12 14:12 UTC, merged